services:
  web1:
    build: .
    container_name: web1
    networks:
      mynetwork:
        ipv4_address: 172.16.0.2
    ports:
      - "8081:80"
    volumes:
      - ./web1:/var/www/html

  web2:
    build: .
    container_name: web2
    networks:
      mynetwork:
        ipv4_address: 172.16.0.3
    ports:
      - "8082:80"
    volumes:
      - ./web2:/var/www/html

  web3:
    build: .
    container_name: web3
    networks:
      mynetwork:
        ipv4_address: 172.16.0.4
    ports:
      - "8083:80"
    volumes:
      - ./web3:/var/www/html

networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
