---
- name: Copy docker file and compose
  gather_facts: false
  hosts: docker
  become: true

  tasks:
    - name: Copy file
      ansible.builtin.copy:
        src: /root/SRC_Projects/docker-compose.yml
        dest: /root

    - name: Copy file
      ansible.builtin.copy:
        src: /root/SRC_Projects/dockerfile
        dest: /root

    - name: Copy file
      ansible.builtin.copy:
        src: /root/SRC_Projects/web1
        dest: /root

    - name: Copy file
      ansible.builtin.copy:
        src: /root/SRC_Projects/web2
        dest: /root

    - name: Copy file
      ansible.builtin.copy:
        src: /root/SRC_Projects/web3
        dest: /root

    - name: Run `docker-compose up` again
      command: docker-compose -f /root/docker-compose.yml up -d
      args:
        chdir: /root


