---
- name: Copy docker file and compose
  gather_facts: false
  hosts: docker
  become: true

  tasks:
    - name: Copy file
      ansible.builtin.copy:
        src: /root/SRC_Projects/docker-compose.yml
        dest: /root/docker-compose.yml

    - name: Copy file
      ansible.builtin.copy:
        src: /root/SRC_Projects/dockerfile
        dest: /root/dockerfile

    - name: Copy file web1
      ansible.builtin.copy:
        src: /root/SRC_Projects/web1
        dest: /root

    - name: Copy file web2
      ansible.builtin.copy:
        src: /root/SRC_Projects/web2
        dest: /root

    - name: Copy file web3
      ansible.builtin.copy:
        src: /root/SRC_Projects/web3
        dest: /root

    - name: Run `docker-compose up` start
      command: docker compose up -d
      args:
        chdir: /root

    - name: Run `docker ps -a`
      command: docker ps -a
      args:
        chdir: /root

